[package]
name = "gbe"
version = "0.1.0"
edition = "2021"

sdl2 = "0.36.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies.sdl2]
version = "0.36.0"
features = ["bundled", "raw-window-handle", "static-link"]
